### ISSUE TITLE
Won't work if we use .focus() without arguments.

### ISSUE THREAD

**Issue by lakesare** [calvellido/focus-options-polyfill#1]
Nice library! Adding `if (args && args.preventScroll) {}` will help, right now it fails if we use `.focus()`.

**Comment by lakesare** [comment]
And `createElement` will always fail, it's not defined in the browser.

**Comment by calvellido** [comment]
Nice, thanks so much @lakesare!

I've addressed your comments in #2, please let me know if you feel we can improve it further, cheers!

**Comment by calvellido** [comment]
Closed through #2
