### ISSUE TITLE
Property document.scrollingElement fallback

### ISSUE THREAD

**Issue by calvellido** [calvellido/focus-options-polyfill#14]
If `document.scrollingElement` doesn't exist, this will throw an error. Example would be in Internet Explorer or when testing with `jest` or anything that uses `jsdom`.

@calvellido As `document.scrollingElement` is `document.documentElement` by default (https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement), would it make sense to fall back to `documentElement` when `scrollingElement` is not found?
```js
parent = document.scrollingElement || document.documentElement
```

* * *

For `jest` users, place this in your test setup file:
```js
document.scrollingElement = document.documentElement
```

_Originally posted by @rpearce in https://github.com/calvellido/focus-options-polyfill/pull/11_

**Comment by calvellido** [comment]
Definitely @rpearce, let me have a look, and I'll try to update the code, release a new version, and update the README.

Many many thanks for the input!

**Comment by calvellido** [comment]
@rpearce, v.1.4.0 tackling this, is now available via [GitHub releases](https://github.com/calvellido/focus-options-polyfill/releases/tag/v.1.4.0) or [npm](https://www.npmjs.com/package/focus-options-polyfill/v/1.4.0).

Let me know if it helps, thanks!

**Comment by rpearce** [comment]
Thanks for the quick work. I'll try it today or tomorrow!
