### ISSUE TITLE
Support iOS Safari?

### ISSUE THREAD

**Issue by galtenberg** [calvellido/focus-options-polyfill#17]
I have not been able to make this polyfill work in iOS Safari - has it been tested there?

Many thanks.

**Comment by calvellido** [comment]
Hi @galtenberg, closest things where this has been checked are MacOS Safari and [Epiphany/GNOME Web (based on WebKit)](https://wiki.gnome.org/Apps/Web) (and I think that probably I wrongly assumed that would suffice for iOS Safari :sweat_smile:). I could eventually test it, but I'm on a bit of a rush lately, so I haven't been able to work further on the polyfill.

Could you share any additional info you got on this, so we can try to triage what's the unsupported function/property in iOS Safari that the polyfill uses?

**Comment by galtenberg** [comment]
@calvellido Unfortunately it's opaque what is happening - the code isn't erroring out / breaking, it just seems to be a no-op. 

I've verified that I can add other event listeners, and I've verified that calling `.focus` directly works. 

If I can get deeper insight via debugging, I'll report back. Just wanted to check. Thanks!

**Comment by galtenberg** [comment]
So I patched your code in manually to see what was going on. iOS Safari _does_ "support" `preventScroll`, so `supportsPreventScrollOption` gets set to `true`. 

But the native `preventScroll` just doesn't work — there's a [bug](https://bugs.webkit.org/show_bug.cgi?id=178583) open for it.

I disabled the `supportsPreventScrollOption` check so the remainder of the code would execute, and the page still scrolls when an input gets focus. 

It would probably require more workarounds to get this working. I'll close this, and will get in contact if I go deeper and get something working.

**Comment by calvellido** [comment]
Many thanks @galtenberg :+1:

**Comment by dminkovsky** [comment]
@galtenberg 

> iOS doesn't have a console to show js issues

iOS does have a console! If you have a device connected by USB or a simulator turned on, you can connect to it with Safari using the "Develop" menu. You have to enable some things in settings (you can search for how) but once you do, you can connect to your iOS device and debug like local. Can even tap an element and it'll appear in the element tree.
