### ISSUE TITLE
There can be a lot more scrolled than just the window element.

### ISSUE THREAD

**Issue by aFarkas** [calvellido/focus-options-polyfill#3]
I implemented something in a very old project. Here is a snippet:

```js
    var calcScrollableElements = function(){
            var parent = element.parentNode;
            while(parent){
                if(parent.offsetHeight < parent.scrollHeight || parent.offsetWidth < parent.scrollWidth){
                    scrollableElements.push([parent, parent.scrollTop, parent.scrollLeft]);
                }
                parent = parent.parentNode;
            }
            parent = document.scrollingElement;
            scrollableElements.push([parent, parent.scrollTop, parent.scrollLeft]);
        };

        var restoreScrollPosition = function(){
            var i;

            for(i = 0; i < scrollableElements.length; i++){
                scrollableElements[i][0].scrollTop = scrollableElements[i][1];
                scrollableElements[i][0].scrollLeft = scrollableElements[i][2];
            }
            scrollableElements = [];
        };
```

**Comment by calvellido** [comment]
Uhmmm, true, didn't really thought about it. This is nice, thanks!

I'm out now, and I won't be able to get the laptop to dig a bit deeper, but I'll be back into it on Monday.

Cheers!

**Comment by mmoss** [comment]
Curious if there's been any more work/traction on the element-level scroll polyfill?

**Comment by calvellido** [comment]
Hi @mmoss, I couldn't work on it after all, but I'll try to have a look at it these days.

Thanks for your interest!

**Comment by calvellido** [comment]
Hi @aFarkas, I'm tackling this in #11. I'll try to do some additional testing before merging it, but it's looking promising. As that's totally based on your code, let me know if you would like to be credited any additional way.

Thanks.
