### ISSUE TITLE
Make `patchedFocus` synchronous

### ISSUE THREAD

**Issue by popeindustries** [calvellido/focus-options-polyfill#31]
We've recently run into a bug related to `patchedFocus()` behaving differently than native `focus()`, where focusing an element is not executed synchronously, and `document.activeElement` is not immediately the element focused. Is there a reason `setTimeout(..., 0)` is used here? Given the `typeof setTimeout === 'function'` check, and subsequent fallback, it would seem that dropping the asynchronous method should probably be the default. 

Thanks for this polyfill, and let me know if you'd like me to make a PR for this!

**Comment by calvellido** [comment]
Hello @popeindustries!

Thanks for waiting for a response. The async method was introduced [here](https://github.com/calvellido/focus-options-polyfill/pull/18) by @kennethormandy, to fix bug #17.

Not sure what would be the current implication of dropping that now, I'd need to check it, but if you are able to, let me know to see if we can reach to a solution working for everything.

Thanks!

**Comment by popeindustries** [comment]
Back from summer vacation, so had a chance to look into this. I can't find a better work around for iOS, and in the process discovered that delaying the `nativeFocus()` call is enough to prevent scroll (`restoreScrollPosition()` call isn't needed), which is very odd, and unfortunate. 

Our current use case is Chrome-only (Samsung TV app), so a vendored copy with the `setTimeout` removed works for us. Thanks for taking the time to reply
