### ISSUE TITLE
Available on NPM?

### ISSUE THREAD

**Issue by rpearce** [calvellido/focus-options-polyfill#6]
Hi, nice polyfill! Is this available through NPM? I can't seem to find it from looking around

**Comment by calvellido** [comment]
Hey!  It has been now published under:

https://www.npmjs.com/package/focus-options-polyfill

Let me know if it's helpful to you, thanks!

**Comment by rpearce** [comment]
Thanks! I'll try it out. I had copied the code temporarily (and given credit), but I'd had to add some "am I in a browser?" checks so that things wouldn't break with server-side rendered JS: https://github.com/rpearce/react-medium-image-zoom/blob/master/source/focus-options-polyfill.js#L4-L10.

That smells like a consumer concern and not yours; however, if you feel differently, let me know!

**Comment by calvellido** [comment]
Hey @rpearce, as it's not something too specific, and it won't add much weight either, I think the browser checking could be a good addition.

I'll do some testing and try to include it this week (#8).

**Comment by calvellido** [comment]
Hey @rpearce, browser checks are now available as part of [v1.2.0](https://github.com/calvellido/focus-options-polyfill/releases/tag/v1.2.0) (also available in [npm](https://www.npmjs.com/package/focus-options-polyfill/v/1.2.0)).

Let me know if it's useful for you!

By the way, when using it through npm, this: [Controlled.js](https://github.com/rpearce/react-medium-image-zoom/blob/master/source/Controlled.js#L9) and this: [Uncontrolled.js](https://github.com/rpearce/react-medium-image-zoom/blob/master/source/Uncontrolled.js#L9) shouldn't be needed, and only importing it:

```js
import 'focus-options-polyfill';
```

would suffice.

**Comment by rpearce** [comment]
@calvellido Thank you! I have an issue for doing this (https://github.com/rpearce/react-medium-image-zoom/issues/208), and was waiting on that! I'll give it a shot tonight.

**Comment by rpearce** [comment]
Update: merged in as of https://github.com/rpearce/react-medium-image-zoom/pull/216
